In [1]:
import pandas as pd
from scipy.stats import pearsonr

In [2]:
df = pd.read_csv('general_data.csv')
df.head()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeID,Gender,...,NumCompaniesWorked,Over18,PercentSalaryHike,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsSinceLastPromotion,YearsWithCurrManager
0,51,No,Travel_Rarely,Sales,6,2,Life Sciences,1,1,Female,...,1.0,Y,11,8,0,1.0,6,1,0,0
1,31,Yes,Travel_Frequently,Research & Development,10,1,Life Sciences,1,2,Female,...,0.0,Y,23,8,1,6.0,3,5,1,4
2,32,No,Travel_Frequently,Research & Development,17,4,Other,1,3,Male,...,1.0,Y,15,8,3,5.0,2,5,0,3
3,38,No,Non-Travel,Research & Development,2,5,Life Sciences,1,4,Male,...,3.0,Y,11,8,3,13.0,5,8,7,5
4,32,No,Travel_Rarely,Research & Development,10,1,Medical,1,5,Male,...,4.0,Y,12,8,2,9.0,2,6,0,4

In [3]:
df['Attrition'].replace(to_replace=('No','Yes'),value=(0,1), inplace=True)
df['Gender'].replace(to_replace=('Male','Female'),value=(0,1), inplace=True)
df.head()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeID,Gender,...,NumCompaniesWorked,Over18,PercentSalaryHike,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsSinceLastPromotion,YearsWithCurrManager
0,51,0,Travel_Rarely,Sales,6,2,Life Sciences,1,1,1,...,1.0,Y,11,8,0,1.0,6,1,0,0
1,31,1,Travel_Frequently,Research & Development,10,1,Life Sciences,1,2,1,...,0.0,Y,23,8,1,6.0,3,5,1,4
2,32,0,Travel_Frequently,Research & Development,17,4,Other,1,3,0,...,1.0,Y,15,8,3,5.0,2,5,0,3
3,38,0,Non-Travel,Research & Development,2,5,Life Sciences,1,4,0,...,3.0,Y,11,8,3,13.0,5,8,7,5
4,32,0,Travel_Rarely,Research & Development,10,1,Medical,1,5,0,...,4.0,Y,12,8,2,9.0,2,6,0,4

In [4]:
# 1. Correlation between Attrition and Age
# Ho : There is no significance difference between Attrition and Age

stats,p = pearsonr(df.Attrition,df.Age)
print("Correlation : ",stats," P-value : ",p)
if p>=0.05:
    print("Accept Null Hypothesis")
elif p<0.05:
    print("Reject Null Hypothesis")
if stats>0:
    print("Positive Correlation")
elif stats<0:
    print("Negative Correlation")

Correlation :  -0.15920500686577965  P-value :  1.996801615886744e-26
Reject Null Hypothesis
Negative Correlation

In [5]:
# 2. Correlation between Attrition and Gender
# Ho : There is no significance difference between Attrition and Gender

stats,p = pearsonr(df.Attrition,df.Gender)
print("Correlation : ",stats," P-value : ",p)
if p>=0.05:
    print("Accept Null Hypothesis")
elif p<0.05:
    print("Reject Null Hypothesis")
if stats>0:
    print("Positive Correlation")
elif stats<0:
    print("Negative Correlation")

Correlation :  -0.01812507887701024  P-value :  0.22881970951795952
Accept Null Hypothesis
Negative Correlation

In [6]:
# 3. Correlation between Attrition and DistanceFromHome
# Ho : There is no significance difference between Attrition and DistanceFromHome

stats,p = pearsonr(df.Attrition,df.DistanceFromHome)
print("Correlation : ",stats," P-value : ",p)
if p>=0.05:
    print("Accept Null Hypothesis")
elif p<0.05:
    print("Reject Null Hypothesis")
if stats>0:
    print("Positive Correlation")
elif stats<0:
    print("Negative Correlation")

Correlation :  -0.00973014101017966  P-value :  0.5182860428050771
Accept Null Hypothesis
Negative Correlation

In [7]:
# 4. Correlation between Attrition and Education
# Ho : There is no significance difference between Attrition and Education

stats,p = pearsonr(df.Attrition,df.Education)
print("Correlation : ",stats," P-value : ",p)
if p>=0.05:
    print("Accept Null Hypothesis")
elif p<0.05:
    print("Reject Null Hypothesis")
if stats>0:
    print("Positive Correlation")
elif stats<0:
    print("Negative Correlation")

Correlation :  -0.015111167710968711  P-value :  0.3157293177118575
Accept Null Hypothesis
Negative Correlation

In [8]:
# 5. Correlation between Attrition and PercentSalaryHike
# Ho : There is no significance difference between Attrition and PercentSalaryHike

stats,p = pearsonr(df.Attrition,df.PercentSalaryHike)
print("Correlation : ",stats," P-value : ",p)
if p>=0.05:
    print("Accept Null Hypothesis")
elif p<0.05:
    print("Reject Null Hypothesis")
if stats>0:
    print("Positive Correlation")
elif stats<0:
    print("Negative Correlation")

Correlation :  0.03253259489105351  P-value :  0.030743386433355353
Reject Null Hypothesis
Positive Correlation

In [9]:
# 6. Correlation between Attrition and StockOptionLevel
# Ho : There is no significance difference between Attrition and StockOptionLevel

stats,p = pearsonr(df.Attrition,df.StockOptionLevel)
print("Correlation : ",stats," P-value : ",p)
if p>=0.05:
    print("Accept Null Hypothesis")
elif p<0.05:
    print("Reject Null Hypothesis")
if stats>0:
    print("Positive Correlation")
elif stats<0:
    print("Negative Correlation")

Correlation :  -0.006838852403261521  P-value :  0.6498072937475723
Accept Null Hypothesis
Negative Correlation

In [10]:
# 7. Correlation between Attrition and TrainingTimesLastYear
# Ho : There is no significance difference between Attrition and TrainingTimesLastYear

stats,p = pearsonr(df.Attrition,df.TrainingTimesLastYear)
print("Correlation : ",stats," P-value : ",p)
if p>=0.05:
    print("Accept Null Hypothesis")
elif p<0.05:
    print("Reject Null Hypothesis")
if stats>0:
    print("Positive Correlation")
elif stats<0:
    print("Negative Correlation")

Correlation :  -0.04943057624425501  P-value :  0.0010247061915362814
Reject Null Hypothesis
Negative Correlation

In [11]:
df.corr()

,Age,Attrition,DistanceFromHome,Education,EmployeeCount,EmployeeID,Gender,JobLevel,MonthlyIncome,NumCompaniesWorked,PercentSalaryHike,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsSinceLastPromotion,YearsWithCurrManager
Age,1.000000,-0.159205,0.006963,-0.035706,NaN,0.008649,0.039352,-0.002884,-0.044314,0.299243,-0.033137,NaN,-0.031753,0.680661,-0.027308,0.311309,0.216513,0.202089
Attrition,-0.159205,1.000000,-0.009730,-0.015111,NaN,-0.004729,-0.018125,-0.010290,-0.031176,0.042345,0.032533,NaN,-0.006839,-0.170338,-0.049431,-0.134392,-0.033019,-0.156199
DistanceFromHome,0.006963,-0.009730,1.000000,-0.008638,NaN,-0.001097,0.044173,-0.037329,-0.021607,-0.013843,0.038125,NaN,0.011169,0.009374,-0.009001,0.031684,0.002290,0.021584
Education,-0.035706,-0.015111,-0.008638,1.000000,NaN,-0.009680,0.016547,0.045746,0.006410,-0.016250,-0.040531,NaN,0.001261,-0.010717,0.010472,0.006080,0.022490,0.005358
EmployeeCount,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EmployeeID,0.008649,-0.004729,-0.001097,-0.009680,NaN,1.000000,0.013165,-0.003303,0.007338,-0.001117,-0.004456,NaN,-0.014254,-0.001063,-0.010191,0.004086,0.000256,0.008579
Gender,0.039352,-0.018125,0.044173,0.016547,NaN,0.013165,1.000000,0.026854,-0.007530,0.066924,-0.011841,NaN,-0.019237,0.027598,0.030167,0.017277,0.021812,-0.004438
JobLevel,-0.002884,-0.010290,-0.037329,0.045746,NaN,-0.003303,0.026854,1.000000,0.047316,-0.009875,0.010973,NaN,0.000993,-0.036957,-0.032500,-0.064219,-0.060811,-0.055251
MonthlyIncome,-0.044314,-0.031176,-0.021607,0.006410,NaN,0.007338,-0.007530,0.047316,1.000000,-0.020726,0.004325,NaN,0.026930,-0.033787,0.050112,0.000995,0.065219,0.024304
NumCompaniesWorked,0.299243,0.042345,-0.013843,-0.016250,NaN,-0.001117,0.066924,-0.009875,-0.020726,1.000000,0.030860,NaN,0.017163,0.238807,-0.032286,-0.117959,-0.036656,-0.109667
PercentSalaryHike,-0.033137,0.032533,0.038125,-0.040531,NaN,-0.004456,-0.011841,0.010973,0.004325,0.030860,1.000000,NaN,0.012548,-0.018736,-0.037392,-0.029707,-0.029542,-0.040864
StandardHours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
StockOptionLevel,-0.031753,-0.006839,0.011169,0.001261,NaN,-0.014254,-0.019237,0.000993,0.026930,0.017163,0.012548,NaN,1.000000,0.002694,-0.069902,0.007886,0.019063,0.017757
TotalWorkingYears,0.680661,-0.170338,0.009374,-0.010717,NaN,-0.001063,0.027598,-0.036957,-0.033787,0.238807,-0.018736,NaN,0.002694,1.000000,-0.040762,0.627703,0.404444,0.458800
TrainingTimesLastYear,-0.027308,-0.049431,-0.009001,0.010472,NaN,-0.010191,0.030167,-0.032500,0.050112,-0.032286,-0.037392,NaN,-0.069902,-0.040762,1.000000,-0.007894,0.016121,-0.013270
YearsAtCompany,0.311309,-0.134392,0.031684,0.006080,NaN,0.004086,0.017277,-0.064219,0.000995,-0.117959,-0.029707,NaN,0.007886,0.627703,-0.007894,1.000000,0.618409,0.769212
YearsSinceLastPromotion,0.216513,-0.033019,0.002290,0.022490,NaN,0.000256,0.021812,-0.060811,0.065219,-0.036656,-0.029542,NaN,0.019063,0.404444,0.016121,0.618409,1.000000,0.510224
YearsWithCurrManager,0.202089,-0.156199,0.021584,0.005358,NaN,0.008579,-0.004438,-0.055251,0.024304,-0.109667,-0.040864,NaN,0.017757,0.458800,-0.013270,0.769212,0.510224,1.000000